openapi: 3.0.0
info:
  title: Trail Management API
  description: API for managing trails and location points.
  version: 1.0.0

servers:
  - url: "/api"

paths:
  /trails:
    get:
      summary: Get all trails
      operationId: trails.read_all_trails
      responses:
        '200':
          description: List of trails
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Trail'
        '404':
          description: No trails found

    post:
      summary: Create a new trail
      operationId: trails.create_trail
      security:
        - BasicAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewTrail'
      responses:
        '201':
          description: Trail created successfully
        '401':
          description: Unauthorized. User needs to log in.
        '403':
          description: Forbidden. Only admins can create trails.

  /trails/{trail_id}/admin:
    get:
      summary: View comprehensive details of a trail (Admin only)
      operationId: trails.read_trail_admin
      security:
        - BasicAuth: []
      parameters:
        - name: trail_id
          in: path
          required: true
          schema:
            type: integer
          description: ID of the trail
      responses:
        '200':
          description: Comprehensive trail details
          content:
            application/json:
              schema:
                type: object
                properties:
                  Trail:
                    $ref: '#/components/schemas/Trail'
                  OwnerID:
                    type: integer
                  Features:
                    type: array
                    items:
                      type: string
                  LocationPoints:
                    type: array
                    items:
                      $ref: '#/components/schemas/LocationPoint'
        '401':
          description: Unauthorized. Admin access required.
        '404':
          description: Trail not found

  /trails/{trail_id}:
    get:
      summary: Get a single trail by ID
      operationId: trails.read_one_trail
      parameters:
        - name: trail_id
          in: path
          required: true
          schema:
            type: string
          description: ID of trail for details
      responses:
        '200':
          description: Trail details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Trail'
        '404':
          description: Trail not found
    put:
      summary: Update a trail by ID
      operationId: trails.update_trail
      security:
        - BasicAuth: []
      parameters:
        - name: trail_id
          in: path
          required: true
          schema:
            type: string
          description: ID of trail to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Trail'
      responses:
        '200':
          description: Trail updated successfully
        '401':
          description: Unauthorized. User needs to log in.
        '403':
          description: Forbidden. Only admins can update trails.
        '404':
          description: Trail not found
    delete:
      summary: Delete a trail by ID
      operationId: trails.delete_trail
      security:
        - BasicAuth: []
      parameters:
        - name: trail_id
          in: path
          required: true
          schema:
            type: string
          description: ID of trail to delete
      responses:
        '200':
          description: Trail deleted successfully
        '401':
          description: Unauthorized. User needs to log in.
        '403':
          description: Forbidden. Only admins can delete trails.
        '404':
          description: Trail not found
    
  /trails/{trail_id}/location_points:
    get:
      summary: Get all location points for a specific trail
      operationId: trails.get_point_locations_for_trail
      parameters:
        - name: trail_id
          in: path
          required: true
          schema:
            type: integer
          description: ID of the trail
      responses:
        '200':
          description: List of location points for the trail
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LocationPoint'
        '404':
          description: Trail not found
    post:
      summary: Add a location point to an existing trail
      operationId: trails.add_location_point_to_trail
      security:
        - BasicAuth: []
      parameters:
        - name: trail_id
          in: path
          required: true
          schema:
            type: integer
          description: ID of the trail
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                Latitude:
                  type: number
                  description: Latitude of the location point
                  minimum: -90
                  maximum: 90
                Longitude:
                  type: number
                  description: Longitude of the location point
                  minimum: -180
                  maximum: 180
                Description:
                  type: string
                  description: Description of the location point
                Order_no:
                  type: integer
                  description: Position of the point in the trail sequence. If not provided, defaults to the next available position.
                  minimum: 1
              required:
                - Latitude
                - Longitude
                - Description
      responses:
        '201':
          description: Location point added successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LocationPoint'
        '400':
          description: |
            Invalid input. Possible reasons include:
            - Order_no out of range
            - Latitude or Longitude outside valid range
            - MAX_DISTANCE exceeded
        '401':
          description: Unauthorized
        '404':
          description: Trail not found
  
  /trails/{trail_id}/location_points/{location_point_id}:
    put:
      summary: Update a location point within a trail
      operationId: trails.update_location_point
      security:
        - BasicAuth: []
      parameters:
        - name: trail_id
          in: path
          required: true
          schema:
            type: integer
          description: ID of the trail
        - name: location_point_id
          in: path
          required: true
          schema:
            type: integer
          description: ID of the location point
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                Latitude:
                  type: number
                  description: New latitude of the location point
                  minimum: -90
                  maximum: 90
                Longitude:
                  type: number
                  description: New longitude of the location point
                  minimum: -180
                  maximum: 180
                Description:
                  type: string
                  description: Updated description of the location point
                Order_no:
                  type: integer
                  description: Updated position of the point in the trail sequence. If not provided, defaults position.
                  minimum: 1
              required:
                - Latitude
                - Longitude
                - Description
      responses:
        '200':
          description: Location point updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LocationPoint'
        '400':
          description:  |
            Invalid input. Possible reasons include:
            - Order_no out of range
            - Latitude or Longitude outside valid range
            - MAX_DISTANCE exceeded
        '401':
          description: Unauthorized
        '404':
          description: Trail or location point not found
    delete:
      summary: Delete a location point from a trail
      operationId: trails.delete_location_point_from_trail
      security:
        - BasicAuth: []
      parameters:
        - name: trail_id
          in: path
          required: true
          schema:
            type: integer
        - name: location_point_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Location point deleted successfully
        '400':
          description: Bad request or location point not associated with the trail
        '401':
          description: Unauthorized. Only admins can delete features.
        '404':
          description: Trail or location point not found

  /trails/{trail_id}/features:
    get:
      summary: Retrieve features for a specific trail
      operationId: trails.get_features_for_trail
      parameters:
        - name: trail_id
          in: path
          required: true
          schema:
            type: integer
          description: ID of the trail
      responses:
        '200':
          description: A list of features for the specified trail
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Feature'
        '404':
          description: Trail not found
    post:
      summary: Add a feature to a trail
      operationId: trails.add_feature_to_trail
      security:
        - BasicAuth: []
      parameters:
        - name: trail_id
          in: path
          required: true
          schema:
            type: integer
          description: ID of the trail
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                Trail_Feature:
                  type: string
              required:
                - Trail_Feature
      responses:
        '201':
          description: Feature added successfully
        '400':
          description: Bad request or feature already exists for trail
        '401':
          description: Unauthorized. Only admins can add features.
        '404':
          description: Trail not found
  
  /trails/{trail_id}/features/{feature_id}:
    put:
      summary: Update a feature
      operationId: trails.update_feature
      security:
        - BasicAuth: []
      parameters:
        - name: trail_id
          in: path
          required: true
          schema:
            type: integer
          description: ID of the trail
        - name: feature_id
          in: path
          required: true
          schema:
            type: integer
          description: ID of the feature to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                Trail_Feature:
                  type: string
              required:
                - Trail_Feature
      responses:
        '200':
          description: Feature updated successfully
        '400':
          description: Feature name already exists or bad request
        '401':
          description: Unauthorized. Only admins can update features.
        '404':
          description: Feature not found
    delete:
      summary: Delete a feature from a trail
      operationId: trails.delete_feature_from_trail
      security:
        - BasicAuth: []
      parameters:
        - name: trail_id
          in: path
          required: true
          schema:
            type: integer
          description: ID of the trail
        - name: feature_id
          in: path
          required: true
          schema:
            type: integer
          description: ID of the feature to delete
      responses:
        '200':
          description: Feature deleted successfully
        '400':
          description: Bad request or feature not associated with the trail
        '401':
          description: Unauthorized. Only admins can delete features.
        '404':
          description: Trail or feature not found

  /location_points:
    get:
      summary: Get all location points
      operationId: trails.read_all_location_points
      responses:
        '200':
          description: List of location points
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LocationPoint'
        '404':
          description: Location points not found

  /location_points/{location_point_id}:
    get:
      summary: Get a location point by ID
      operationId: trails.get_location_points
      parameters:
        - name: location_point_id
          in: path
          required: true
          schema:
            type: integer
          description: ID of Location Point to get information
      responses:
        '200':
          description: Location point details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LocationPoint'
        '404':
          description: Location point not found

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
      x-basicInfoFunc: "authentication.authenticate_user"

  schemas:
    NewTrail:
      type: object
      properties:
        Trail_name:
          type: string
          maxLength: 100
          minLength: 3
        Trail_Summary:
          type: string
          maxLength: 255
        Trail_Description:
          type: string
          maxLength: 255
        Difficulty:
          type: string
          enum: [Easy, Moderate, Hard]
          default: Easy
        Location:
          type: string
          maxLength: 100
        Length:
          type: number
          minimum: 0
        Elevation_gain:
          type: number
          minimum: 0
        Route_type:
          type: string
        LocationPoints:
          type: array
          items:
            type: object
            properties:
              Latitude:
                type: number
                minimum: -90
                maximum: 90
              Longitude:
                type: number
                minimum: -180
                maximum: 180
              Description:
                type: string
      required:
        - Trail_name
        - Difficulty
        - Location
        - Length
        - LocationPoints

    Trail:
      type: object
      properties:
        TrailID:
          type: integer
        Trail_name:
          type: string
        Trail_Summary:
          type: string
        Trail_Description:
          type: string
        Difficulty:
          type: string
        Location:
          type: string
        Length:
          type: number
          minimum: 0
        Elevation_gain:
          type: number
          minimum: 0
        Route_type:
          type: string

    TrailDetails:
      type: object
      properties:
        Trail:
          $ref: '#/components/schemas/Trail'
        OwnerID:
          type: integer
        Features:
          type: array
          items:
            $ref: '#/components/schemas/Feature'
        LocationPoints:
          type: array
          items:
            $ref: '#/components/schemas/LocationPoint'

    LocationPoint:
      type: object
      properties:
        Location_Point:
          type: integer
        Order_no:
          type: integer
        Latitude:
          type: number
          minimum: -90
          maximum: 90
        Longitude:
          type: number
          minimum: -180
          maximum: 180
        Description:
          type: string
        timestamp:
          type: string
          format: date-time
      required:
        - Location_Point
        - Latitude
        - Longitude

    Feature:
      type: object
      properties:
        FeatureID:
          type: integer
        Trail_Feature:
          type: string
      required:
        - Trail_Feature
