openapi: 3.0.0
info:
  title: Trail Management API
  description: API for managing trails and location points.
  version: 1.0.0

servers:
  - url: "/api"

paths:
  /trails:
    get:
      summary: Get all trails
      operationId: trails.read_all_trails
      responses:
        '200':
          description: List of trails
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Trail'
    post:
      summary: Create a new trail
      operationId: trails.create_trail
      security:
        - BasicAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewTrail'
      responses:
        '201':
          description: Trail created successfully
        '401':
          description: Unauthorized. User needs to log in.
        '403':
          description: Forbidden. Only admins can create trails.

  /trails/{trail_id}:
    get:
      summary: Get a single trail by ID
      operationId: trails.read_one_trail
      parameters:
        - name: trail_id
          in: path
          required: true
          schema:
            type: string
          description: ID of trail for details
      responses:
        '200':
          description: Trail details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Trail'
        '404':
          description: Trail not found
    put:
      summary: Update a trail by ID
      operationId: trails.update_trail
      security:
        - BasicAuth: []
      parameters:
        - name: trail_id
          in: path
          required: true
          schema:
            type: string
          description: ID of trail to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Trail'
      responses:
        '200':
          description: Trail updated successfully
        '401':
          description: Unauthorized. User needs to log in.
        '403':
          description: Forbidden. Only admins can update trails.
        '404':
          description: Trail not found
    delete:
      summary: Delete a trail by ID
      operationId: trails.delete_trail
      security:
        - BasicAuth: []
      parameters:
        - name: trail_id
          in: path
          required: true
          schema:
            type: string
          description: ID of trail to delete
      responses:
        '200':
          description: Trail deleted successfully
        '401':
          description: Unauthorized. User needs to log in.
        '403':
          description: Forbidden. Only admins can delete trails.
        '404':
          description: Trail not found

  /locations:
    get:
      summary: Get all location points
      operationId: trails.read_all_locations
      responses:
        '200':
          description: List of location points
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LocationPoint'
        '404':
          description: Location points not found

  /location_points/{location_point_id}:
    get:
      summary: Get a location point by ID
      operationId: trails.get_location
      parameters:
        - name: location_point_id
          in: path
          required: true
          schema:
            type: integer
          description: ID of Location Point to get information
      responses:
        '200':
          description: Location point details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LocationPoint'
        '404':
          description: Location point not found
    put:
      summary: Update a location point by ID
      operationId: trails.update_location
      security:
        - BasicAuth: []
      parameters:
        - name: location_point_id
          in: path
          required: true
          schema:
            type: integer
          description: ID of Location Point to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LocationPoint'
      responses:
        '200':
          description: Location point updated successfully
        '401':
          description: Unauthorized. User needs to log in.
        '403':
          description: Forbidden. Only admins can update location points.
        '404':
          description: Location point not found

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
      x-basicInfoFunc: "authentication.authenticate_user"

  schemas:
    NewTrail:
      type: object
      properties:
        Trail_name:
          type: string
        Trail_Summary:
          type: string
        Trail_Description:
          type: string
        Difficulty:
          type: string
        Location:
          type: string
        Length:
          type: number
        Elevation_gain:
          type: number
        Route_type:
          type: string
      required:
        - Trail_name
        - Difficulty
        - Location
        - Length
    Trail:
      type: object
      properties:
        TrailID:
          type: integer
        Trail_name:
          type: string
        Trail_Summary:
          type: string
        Trail_Description:
          type: string
        Difficulty:
          type: string
        Location:
          type: string
        Length:
          type: number
        Elevation_gain:
          type: number
        Route_type:
          type: string
    LocationPoint:
      type: object
      properties:
        Location_Point:
          type: integer
        Latitude:
          type: number
        Longitude:
          type: number
        Description:
          type: string
